name-template: "Release v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: 🚀 New Features
    labels:
      - feature
      - enhancement

  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix

  - title: 🛠️ Maintenance
    labels:
      - chore
      - refactor

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

template: |
  ## 🚀 Features
  $CHANGES

  **Contributors:**  
  $CONTRIBUTORS
