name: Manual Test Environment Deployment

on:
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "checkout code"

      - name: Set up JDK
        run: echo "setup jdk"


      - name: Build Spring Boot App
        run: echo "Gradle build"

      - name: Deploy to Test Environment
        run: echo "Deployed to Test"
